sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6_0.gemfile
before_install: gem install bundler -v '~> 2.1.4'
